# Run continuous integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'
          check-latest: false
          cache: 'maven'
      - name: Test with Maven
        run: 'mvn clean test'
      - name: Run SpotBugs
        run: 'mvn com.github.spotbugs:spotbugs-maven-plugin:check'
